apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-bandwidth-simulator
  labels:
    app: latency-bandwidth-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency-bandwidth-simulator
  template:
    metadata:
      labels:
        app: latency-bandwidth-simulator
    spec:
      containers:
      - name: latency-bandwidth-simulator
        image: dimitrisgian/latency-bandwidth-simulator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: latency-bandwidth-simulator
spec:
  selector:
    app: latency-bandwidth-simulator
  ports:
    - protocol: TCP
      port: 3000       # Service port
      targetPort: 3000 # Container port
      nodePort: 31234  # NodePort to expose
  type: NodePort
